### ISSUE TITLE
props spread?

### ISSUE THREAD

**Issue by bbruneau** [pugjs/babel-plugin-transform-react-pug#11]
Is there a plan to allow a generic props spread, a la
```
<SomeComponent {...props} />
```
?

**Comment by ljbc1994** [comment]
Hi, props spread is supported. Eg:

### In
```js
const App = (props) => pug`
  .app(...props) Contents
`
```

### Out
```js
const App = (props) => {
  return <div {...props} className="app">Contents</div>
}
```

**Comment by bbruneau** [comment]
Ah, great.

**Comment by jhessin** [comment]
Please reopen this issue.
Prop spread doesn't work in conjunction with any other props (which is used for Animation in conjunction with gestures) i.e.

```
<Animated.View
            key={item.id}
            style={[this.getCardStyle(), styles.cardStyle, { zIndex: 99 }]}
            {...this.state.panResponder.panHandlers}
          >
            {this.props.renderCard(item)}
</Animated.View>
```

**Comment by ljbc1994** [comment]
Could you provide an example of when it doesn't work in conjunction with other props?

If you try the following, it should work:

```js
import { Animated } from 'react-native';
const AnimatedView = Animated.View;

// rest of code

const viewStyles = [this.getCardStyles(), styles.cardStyle, {zIndex: 99}])

pug`
  AnimatedView(key=item.id, style=viewStyles, ...this.state.panResponder.panHandlers)  
`
```

I believe it's another issue causing the problem as the `Animated.View` doesn't work when used in conjunction with pug, this is because it conflicts with the way class names are defined. i.e.

```js
pug`
  Animated.View
`
```

will become:

```js
<Animated className="View" />
```
