### ISSUE TITLE
Is babel-plugin-transform-react-jsx plugin really required

### ISSUE THREAD

**Issue by mars-abd** [pugjs/babel-plugin-transform-react-pug#18]
Is babel-plugin-transform-react-jsx plugin really required? I have not read the sources, but I have thought that:
```
p This is my component using pug
```
will be compiled directly to:
```
React.createElement('p', null, 'This is my component using pug');
```
without jsx

**Comment by ezhlobo** [comment]
@mars-abd I don't know exactly but I can provide possible answers:

* pugjs transpiles own syntax into html, so it's easier to make target html suitable with jsx than with other format
* sticking with jsx (instead of react) has a huge benefit: you can use it with different libraries which support jsx (like react and vue).

**Comment by mars-abd** [comment]
Thanks for the answer!

**Comment by ForbesLindesay** [comment]
Yes, we list the jsx transform as part of the README, so I don't think any further action is required here.

We generate our JSX and rely on the JSX transform for a few reasons:

1. The React team have changed the element creation API in the past, using JSX insulates us from those changes.
2. There are other libraries that use JSX for different targets, these can be supported by react-pug by simply swapping out the jsx transform for something else.
3. There are a number of optimisations (e.g. constant elements) that are currently only supported when applied to JSX, not calls to `React.createElement`. By generating JSX, react-pug is compatible with these.
