### ISSUE TITLE
className

### ISSUE THREAD

**Issue by wh-Coder** [pugjs/babel-plugin-transform-react-pug#57]
Know from the documentation：

React.Fragment becomes \<React className="Fragment" /\>

but in RN Use braces instead of quotes:

\<React className={Fragment} /\> or \<React className={[Fragment1, Fragment2]}/\>

**Comment by ezhlobo** [comment]
@wh-Coder that's tricky, because ideally we need to convert `React.Fragment` into `<React.Fragment />`. Not to `<React className="Fragment" />` or `<React className={Fragment} />`.

To set class names for RN you can define classes as you do with JSX:

```pug
View(class=styles.wrapper)
  Text(class=styles.text)
```

If I misunderstood your concern, could you give more details?

**Comment by ForbesLindesay** [comment]
This isn't a react vs. react native thing. The syntax is exactly the same for React vs. React Native. `<Foo bar="value" />` is a shorthand for `<Foo bar={'value'} />` and is supported on all React platforms. It just means that it's the literal string, not the value of a variable.
